# Importando Libs e lendo o arquivo

In [132]:
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display


df_test = pd.read_csv('../chars/data/dataset_comparacao_modelos.csv')
df_test

,Ano,PIB per capita (US$),Apoio Social,Expectativa de vida,Liberdade de escolhas,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional,Índice Real,LR Previsto,RF Previsto,XGB Previsto,País
0,2016,8.381088,0.615449,55.224998,0.785907,-0.087659,0.790386,0.586020,0.303667,0.483075,4.119493,4.364996,4.578516,4.649117,Congo (Brazzaville)
1,2017,7.335250,0.684867,53.700001,0.733390,-0.014268,0.866806,0.673802,0.391331,0.554992,4.424491,4.124929,4.358680,4.350938,Liberia
2,2009,9.916162,0.831582,68.320000,0.746614,0.143405,0.734211,0.755948,0.299891,0.575284,6.493686,6.130261,6.150739,6.062838,Chile
3,2019,9.536200,0.847720,56.200001,0.738339,-0.144647,0.819824,0.727414,0.268456,0.495906,5.034863,5.386849,4.757850,4.635128,South Africa
4,2007,7.367519,0.478951,47.459999,0.294612,-0.013500,0.873610,0.597517,0.245208,0.228145,4.141327,3.352283,3.599540,3.711648,Chad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,2011,7.232430,0.612737,50.660000,0.733464,0.073304,0.852994,0.619638,0.268475,0.419559,3.946063,3.958021,4.181721,4.255391,Malawi
436,2017,7.587157,0.507805,55.200001,0.716694,-0.062541,0.725520,0.614388,0.425824,0.484952,4.360805,3.944961,3.608248,4.170554,Togo
437,2011,10.534597,0.843655,70.959999,0.745469,0.175205,0.840676,0.682391,0.272300,0.399998,6.689609,6.295202,6.337928,6.388786,Cyprus
438,2015,9.441860,0.517372,64.199997,0.639945,-0.207957,0.502417,0.447714,0.233192,0.254327,4.121941,4.727052,4.369612,4.095459,Georgia
439,2012,6.980212,0.700108,52.779999,0.734431,-0.064104,0.777341,0.582122,0.141553,0.534528,3.798088,3.916679,4.039682,4.026940,Niger

# Gráficos

## Comparativo de previsões com índice real

In [133]:

# Lista de países para o dropdown
paises = sorted(df_test["País"].unique())
dropdown_pais = widgets.Dropdown(options=paises, value=paises[0], description="País")

def plot_modelos(pais):
   dados = df_test[df_test["País"] == pais]
   
   # média por garantia, caso tenha mais de um ano por país
   valores = dados[["Índice Real", "LR Previsto", "RF Previsto", "XGB Previsto"]].mean()
   modelos = valores.index.tolist()
   numeros = valores.values
   
   plt.figure(figsize=(6,4))
   plt.bar(modelos, numeros)
   plt.ylim(0, 10)
   plt.ylabel("Índice de Felicidade")
   plt.title(f"Comparação de Previsões para {pais}")
   plt.xticks(rotation=15)
   plt.tight_layout()
   plt.show()

widgets.interact(plot_modelos, pais=dropdown_pais);

interactive(children=(Dropdown(description='País', options=('Afghanistan', 'Albania', 'Algeria', 'Argentina', …

## Evolução da felicidade ao longo dos anos

### Lendo o Dataset

In [134]:
df = pd.read_csv('../data/processed/world_happiness_report_colunas_pt_preprocessed.csv')

df_evolucao = df.copy()
df_evolucao

,País,Ano,Índice de Felicidade,PIB per capita (US$),Apoio Social,Expectativa de vida,Liberdade de escolhas,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,0.476866

In [135]:


# Dropdown de países
paises = sorted(df_evolucao["País"].unique())
dropdown_pais = widgets.Dropdown(options=paises, value=paises[0], description="País")

def plot_evolucao(pais):
   # filtra o país
   dados = df_evolucao[df_evolucao["País"] == pais].copy()
   
   # garante que está ordenado por ano e, se tiver mais de uma linha por ano, tira a média
   dados = (
      dados.groupby("Ano", as_index=False)["Índice de Felicidade"]
      .mean()
      .sort_values("Ano")
   )

   plt.figure(figsize=(7,4))
   plt.plot(dados["Ano"], dados["Índice de Felicidade"], marker="o")
   plt.title(f"Evolução do Índice de Felicidade em {pais}")
   plt.xlabel("Ano")
   plt.ylabel("Índice de Felicidade")
   plt.ylim(0, 10)
   plt.grid(alpha=0.3)
   plt.xticks(rotation=45)
   plt.tight_layout()
   plt.show()

widgets.interact(plot_evolucao, pais=dropdown_pais);

interactive(children=(Dropdown(description='País', options=('Afghanistan', 'Albania', 'Algeria', 'Angola', 'Ar…

## Mapa de calor Global

In [136]:
import geopandas as gpd

url = "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"

world = gpd.read_file(url)
world = world.to_crs("EPSG:4326")  # garante projeção geográfica
world.head()

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,TLC,ADMIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
0,Admin-0 country,1,6,Fiji,FJI,0,2,Sovereign country,1,Fiji,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((180 -16.06713, 180 -16.55522, ..."
1,Admin-0 country,1,3,United Republic of Tanzania,TZA,0,2,Sovereign country,1,United Republic of Tanzania,...,None,None,None,None,None,None,None,None,None,"POLYGON ((33.90371 -0.95, 34.07262 -1.05982, 3..."
2,Admin-0 country,1,7,Western Sahara,SAH,0,2,Indeterminate,1,Western Sahara,...,Unrecognized,Unrecognized,Unrecognized,None,None,Unrecognized,None,None,None,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,Admin-0 country,1,2,Canada,CAN,0,2,Sovereign country,1,Canada,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -122.97421 49.0025..."
4,Admin-0 country,1,2,United States of America,US1,1,2,Country,1,United States of America,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -120 49, -117.0312..."

In [137]:
dropdown_pais = widgets.Dropdown(options=paises, value=paises[0], description="País")

In [138]:
# Coluna com o nome de país no shapefile (pode ser ADMIN ou NAME)
country_col = "ADMIN"  # ajuste se necessário

# Países do dataset
paises_df = set(df["País"].unique())

# Países do shapefile
paises_mapa = set(world[country_col].unique())

# Países que não batem
nao_batem = sorted(paises_df - paises_mapa)
nao_batem[:50]  # mostra alguns

['Bahrain',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Eswatini',
 'Hong Kong S.A.R. of China',
 'Maldives',
 'Malta',
 'Mauritius',
 'Serbia',
 'Singapore',
 'Somaliland region',
 'State of Palestine',
 'Taiwan Province of China',
 'Tanzania',
 'Turkiye',
 'United States']

In [139]:
dropdown_pais = widgets.Dropdown(options=paises, value=paises[0], description="País")

In [140]:
correcao_paises = {
    "United States": "United States of America",
    "Congo (Kinshasa)": "Democratic Republic of the Congo",
    "Congo (Brazzaville)": "Republic of the Congo",
    "Eswatini": "eSwatini",
    "Hong Kong S.A.R. of China": "Hong Kong",
    "State of Palestine": "Palestine",
    "Taiwan Province of China": "Taiwan",
    "Tanzania": "Tanzania",
    "Turkiye": "Turkey",
    "Somaliland region": None,     # Não reconhecido como país no mapa (fica cinza)
    "Comoros": "Comoros",
    "Maldives": "Maldives",
    "Mauritius": "Mauritius",
    "Malta": "Malta",
    "Bahrain": "Bahrain",
    "Serbia": "Serbia",
    "Singapore": "Singapore"
}

In [141]:
df["País"] = df["País"].replace(correcao_paises)

In [142]:
world.columns

Index(['featurecla', 'scalerank', 'LABELRANK', 'SOVEREIGNT', 'SOV_A3',
       'ADM0_DIF', 'LEVEL', 'TYPE', 'TLC', 'ADMIN',
       ...
       'FCLASS_TR', 'FCLASS_ID', 'FCLASS_PL', 'FCLASS_GR', 'FCLASS_IT',
       'FCLASS_NL', 'FCLASS_SE', 'FCLASS_BD', 'FCLASS_UA', 'geometry'],
      dtype='object', length=169)

In [143]:
country_col = "ADMIN"

In [144]:
# nao_batem = sorted(set(df["País"].unique()) - set(world[country_col].unique()))
# nao_batem

### Lendo o Dataset

In [145]:
df_mapa = df.copy()

In [ ]:
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

# Defina aqui a coluna de nome de país no shapefile
country_col = "ADMIN"  # troque se for NAME ou outra

# Dataset de felicidade: País, Ano, Índice de Felicidade
df_mapa = df_mapa.copy()
df_mapa = df_mapa.groupby(["País", "Ano"], as_index=False)["Índice de Felicidade"].mean()

# Dropdown de anos
anos = sorted(df_mapa["Ano"].unique())
dropdown_ano = widgets.Dropdown(options=anos, value=anos[-1], description="Ano")

def plot_mapa(ano):
   dados_ano = df_mapa[df_mapa["Ano"] == ano]

   # Join entre shapefile e dados (atenção no country_col)
   mapa = world.merge(dados_ano, left_on=country_col, right_on="País", how="left")

   plt.figure(figsize=(14, 6))
   ax = plt.gca()
   ax.set_title(f"Índice Médio de Felicidade Mundial – {ano}", fontsize=14)
   mapa.plot(
      column="Índice de Felicidade",
      cmap="viridis",
      linewidth=0.3,
      edgecolor="black",
      legend=True,
      missing_kwds={"color": "lightgray", "label": "Sem dados"},
      ax=ax
   )
   ax.set_axis_off()
   plt.show()

widgets.interact(plot_mapa, ano=dropdown_ano);

interactive(children=(Dropdown(description='Ano', index=17, options=(np.int64(2005), np.int64(2006), np.int64(…